using System.Text.Json;
using System.Text.Json.Serialization;

namespace CodingWithCalvin.VSToolbox.Services;

public sealed class WindowsTerminalService
{
    private static readonly string SettingsPath = Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
        "Packages",
        "Microsoft.WindowsTerminal_8wekyb3d8bbwe",
        "LocalState",
        "settings.json");

    public bool IsWindowsTerminalInstalled() => File.Exists(SettingsPath);

    public IReadOnlyList<TerminalProfile> GetProfiles()
    {
        if (!IsWindowsTerminalInstalled())
        {
            return [];
        }

        try
        {
            var json = File.ReadAllText(SettingsPath);
            var settings = JsonSerializer.Deserialize<WtSettings>(json, JsonOptions);

            if (settings?.Profiles?.List is null)
            {
                return [];
            }

            return settings.Profiles.List
                .Where(p => !p.Hidden)
                .Where(p => !IsWslProfile(p) && !IsVsDebugConsole(p) && !IsVsAutoGeneratedProfile(p))
                .Select(p => new TerminalProfile
                {
                    Guid = p.Guid,
                    Name = p.Name,
                    ShellType = DetermineShellType(p)
                })
                .Where(p => p.ShellType != ShellType.Unknown)
                .ToList();
        }
        catch
        {
            return [];
        }
    }

    private static bool IsWslProfile(WtProfile profile) =>
        profile.Source?.Contains("WSL", StringComparison.OrdinalIgnoreCase) == true;

    private static bool IsVsDebugConsole(WtProfile profile) =>
        profile.Source?.Contains("VSDebugConsole", StringComparison.OrdinalIgnoreCase) == true;

    private static bool IsVsAutoGeneratedProfile(WtProfile profile) =>
        profile.Source?.Contains("Windows.Terminal.VisualStudio", StringComparison.OrdinalIgnoreCase) == true;

    private static ShellType DetermineShellType(WtProfile profile)
    {
        // Check source first
        if (!string.IsNullOrEmpty(profile.Source))
        {
            if (profile.Source.Contains("PowershellCore", StringComparison.OrdinalIgnoreCase))
                return ShellType.PowerShell;
        }

        // Check commandline
        if (!string.IsNullOrEmpty(profile.Commandline))
        {
            if (profile.Commandline.Contains("pwsh", StringComparison.OrdinalIgnoreCase) ||
                profile.Commandline.Contains("powershell", StringComparison.OrdinalIgnoreCase))
                return ShellType.PowerShell;

            if (profile.Commandline.Contains("cmd", StringComparison.OrdinalIgnoreCase))
                return ShellType.Cmd;
        }

        // Check name as fallback
        if (!string.IsNullOrEmpty(profile.Name))
        {
            if (profile.Name.Contains("PowerShell", StringComparison.OrdinalIgnoreCase))
                return ShellType.PowerShell;

            if (profile.Name.Contains("Command Prompt", StringComparison.OrdinalIgnoreCase) ||
                profile.Name.Contains("CMD", StringComparison.OrdinalIgnoreCase))
                return ShellType.Cmd;
        }

        return ShellType.Unknown;
    }

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true,
        ReadCommentHandling = JsonCommentHandling.Skip,
        AllowTrailingCommas = true
    };

    private sealed class WtSettings
    {
        public WtProfiles? Profiles { get; set; }
    }

    private sealed class WtProfiles
    {
        public List<WtProfile>? List { get; set; }
    }

    private sealed class WtProfile
    {
        public string Guid { get; set; } = string.Empty;
        public string Name { get; set; } = string.Empty;
        public string? Source { get; set; }
        public string? Commandline { get; set; }
        public bool Hidden { get; set; }
    }
}

public sealed class TerminalProfile
{
    public required string Guid { get; init; }
    public required string Name { get; init; }
    public required ShellType ShellType { get; init; }
}

public enum ShellType
{
    Unknown,
    Cmd,
    PowerShell
}
